---
# tasks file for selinux
- name: enable permissive mode
  become: true
  selinux:
    policy: targeted
    state: permissive
- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  become: true
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
- name: Set httpd_unified flag on and keep it persistent across reboots
  become: true
  seboolean:
    name: httpd_unified
    state: yes
    persistent: yes
- name: fix label on /etc/ld.so.cache
  become: true
  shell: "/sbin/restorecon -v /etc/ld.so.cache"
- name: fix sedispatch access
  become: true
  shell: "ausearch -c '/usr/sbin/sedispatch' --raw | audit2allow -M my-sedispatch # semodule -i my-sedispatch.pp"
- name: clear the selinux log
  become: true
  shell: "> /var/log/audit/audit.log"
- name: Unconditionally reboot the machine with all defaults
  become: true
  reboot:
- name: enable enforcing mode
  become: true
  selinux:
    policy: targeted
    state: enforcing
